package TelasAplicacao;

import Maquina.Maquina;
import Maquina.MaquinaCrud;
import Componentes.Componente;
import Componentes.ComponenteCrud;
import Usuarios.UsuarioCrud;
import java.net.SocketException;
import java.net.UnknownHostException;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import org.apache.commons.dbcp2.BasicDataSource;
import java.awt.Color;
import javax.swing.JOptionPane;

/**
 *
 * @author fabio.gdesouza
 */
public class TelaFuncMaq extends javax.swing.JFrame {

    BasicDataSource dataSource = new BasicDataSource();
    
    public String login;
    public String nome;
    

    /**
     * Creates new form TelaFuncMaq
     */
    public TelaFuncMaq() {
        initComponents();
        setLocationRelativeTo(this);
    }

    public TelaFuncMaq(UsuarioCrud usuario) {
        initComponents();
        setLocationRelativeTo(this);

        login = usuario.getLoginUsuario();
        nome = usuario.getUsuario();
        String texto = "Bem vindo(a) " + nome + "!";
        labelNomeUsuario.setText(texto);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        bttRetornar = new javax.swing.JButton();
        labelMostrarErro = new javax.swing.JLabel();
        labelNomeUsuario = new javax.swing.JLabel();
        labelIniciar = new javax.swing.JLabel();
        bttHardware = new javax.swing.JButton();
        bttCadastrar = new javax.swing.JButton();
        labelHardware = new javax.swing.JLabel();
        labelCadastrar = new javax.swing.JLabel();
        bttStart = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        bttRetornar.setBackground(new java.awt.Color(0, 0, 0));
        bttRetornar.setForeground(new java.awt.Color(255, 255, 255));
        bttRetornar.setText("Deslogar");
        bttRetornar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttRetornarActionPerformed(evt);
            }
        });
        jPanel1.add(bttRetornar, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 450, 80, 30));

        labelMostrarErro.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        labelMostrarErro.setForeground(new java.awt.Color(204, 0, 0));
        labelMostrarErro.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel1.add(labelMostrarErro, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 410, 450, 70));

        labelNomeUsuario.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        labelNomeUsuario.setForeground(new java.awt.Color(255, 255, 255));
        labelNomeUsuario.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelNomeUsuario.setText("Bem Vindo!");
        labelNomeUsuario.setPreferredSize(new java.awt.Dimension(149, 20));
        jPanel1.add(labelNomeUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 180, 450, 40));

        labelIniciar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        labelIniciar.setForeground(new java.awt.Color(255, 255, 255));
        labelIniciar.setText("Iniciar Aplicação Java:");
        jPanel1.add(labelIniciar, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 220, 250, 50));

        bttHardware.setBackground(new java.awt.Color(0, 0, 0));
        bttHardware.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        bttHardware.setForeground(new java.awt.Color(255, 255, 255));
        bttHardware.setText("Hardware");
        bttHardware.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttHardwareActionPerformed(evt);
            }
        });
        jPanel1.add(bttHardware, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 360, 120, 40));

        bttCadastrar.setBackground(new java.awt.Color(0, 0, 0));
        bttCadastrar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        bttCadastrar.setForeground(new java.awt.Color(255, 255, 255));
        bttCadastrar.setText("Cadastrar");
        bttCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttCadastrarActionPerformed(evt);
            }
        });
        jPanel1.add(bttCadastrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 360, 120, 40));

        labelHardware.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        labelHardware.setForeground(new java.awt.Color(255, 255, 255));
        labelHardware.setText("Listar Hardware:");
        jPanel1.add(labelHardware, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 310, 120, 50));

        labelCadastrar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        labelCadastrar.setForeground(new java.awt.Color(255, 255, 255));
        labelCadastrar.setText("Cadastrar Máquina:");
        jPanel1.add(labelCadastrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 310, 120, 50));

        bttStart.setBackground(new java.awt.Color(0, 0, 0));
        bttStart.setForeground(new java.awt.Color(255, 255, 255));
        bttStart.setText("Start");
        bttStart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttStartActionPerformed(evt);
            }
        });
        jPanel1.add(bttStart, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 270, 250, 40));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Logo_Observium_Branco.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 50, -1, -1));

        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/FundoObservium2.jpg"))); // NOI18N
        background.setText("jLabel1");
        jPanel1.add(background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 610, 490));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bttCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttCadastrarActionPerformed
        try {
            if(!verificarSeComputadorEstaCadastrado()){
                BasicDataSource dataSource = new BasicDataSource();
                UsuarioCrud usuario = new UsuarioCrud(dataSource);
                String nomeUsuario = usuario.buscarNomeUsuario(login);
                usuario.setUsuario(nomeUsuario);
                TelaCadMaq cadastroMaq = new TelaCadMaq(usuario);
                this.dispose();
                cadastroMaq.setVisible(true);
            } else {
                JOptionPane.showMessageDialog(this, "Máquina já cadastrada!");
            }
        } catch (UnknownHostException ex) {
            Logger.getLogger(TelaFuncMaq.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SocketException ex) {
            Logger.getLogger(TelaFuncMaq.class.getName()).log(Level.SEVERE, null, ex);
        } catch (InterruptedException ex) {
            Logger.getLogger(TelaFuncMaq.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
        
    }//GEN-LAST:event_bttCadastrarActionPerformed

    private void bttStartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttStartActionPerformed
        BasicDataSource dataSource = new BasicDataSource();

        UsuarioCrud usuario = new UsuarioCrud(dataSource);

        String nomeUsuario = usuario.buscarNomeUsuario(login);
        usuario.setUsuario(nomeUsuario);
        TelaCaptura registro = new TelaCaptura(usuario);
        this.dispose();
        registro.setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_bttStartActionPerformed

    private void bttHardwareActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttHardwareActionPerformed
        try {
            BasicDataSource dataSource = new BasicDataSource();

            UsuarioCrud usuario = new UsuarioCrud(dataSource);
            
            String nomeUsuario = usuario.buscarNomeUsuario(login);
            usuario.setUsuario(nomeUsuario);
            TelaHardware hardware = new TelaHardware(usuario);
            this.dispose();
            hardware.setVisible(true);
        } catch (UnknownHostException ex) {
            Logger.getLogger(TelaFuncMaq.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SocketException ex) {
            Logger.getLogger(TelaFuncMaq.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_bttHardwareActionPerformed

    private void bttRetornarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttRetornarActionPerformed
        TelaLoginFunc telaLogin = new TelaLoginFunc();
        this.dispose();
        telaLogin.setVisible(true);
    }//GEN-LAST:event_bttRetornarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaFuncMaq.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaFuncMaq.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaFuncMaq.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaFuncMaq.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaFuncMaq().setVisible(true);
            }
        });
    }
    
    public static Boolean verificarSeComputadorEstaCadastrado() throws InterruptedException, UnknownHostException, SocketException {
        BasicDataSource dataSource = new BasicDataSource();
        MaquinaCrud maquinaCRUD = new MaquinaCrud(dataSource);
        String hostname = maquinaCRUD.buscarHostName();
        ComponenteCrud compCRUD = new ComponenteCrud(dataSource);

        //if (maquinaCRUD.buscarIdComputadorNuvem(hostname) != 0) {
            if(maquinaCRUD.buscarIdComputadorLocal(hostname) != 0){
                 return true;
            //}
           //return false;
        } else {
            return false;
        }

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel background;
    private javax.swing.JButton bttCadastrar;
    private javax.swing.JButton bttHardware;
    private javax.swing.JButton bttRetornar;
    private javax.swing.JButton bttStart;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel labelCadastrar;
    private javax.swing.JLabel labelHardware;
    private javax.swing.JLabel labelIniciar;
    private javax.swing.JLabel labelMostrarErro;
    private javax.swing.JLabel labelNomeUsuario;
    // End of variables declaration//GEN-END:variables
}
