/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package TelasAplicacao;

import Componentes.AlertaSlack;
import Componentes.AppMonitoramento;
import java.awt.Color;
import java.net.SocketException;
import java.net.UnknownHostException;
import java.util.logging.Level;
import java.util.logging.Logger;
import Usuarios.UsuarioCrud;
import java.awt.event.ActionListener;
import java.util.TimerTask;
import java.util.Timer;
import org.apache.commons.dbcp2.BasicDataSource;

/**
 *
 * @author fabio.gdesouza
 */
public class TelaCaptura extends javax.swing.JFrame {
    
    BasicDataSource dataSource = new BasicDataSource();
    Timer timer = new Timer();
    
    Color azulObservium = Color.decode("#2689b9");
    
    public String login;
    
    /**
     * Creates new form TelaCaptura
     */
    public TelaCaptura() {
        initComponents();
        setLocationRelativeTo(this);
        bttStopApp.setEnabled(false);
    }
    
    public TelaCaptura(UsuarioCrud usuario) {
        initComponents();
        setLocationRelativeTo(this);
        bttStopApp.setEnabled(false);
        
        login = usuario.getLoginUsuario();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        gifCarregando = new javax.swing.JLabel();
        bttRetornar = new javax.swing.JButton();
        bttStopApp = new javax.swing.JButton();
        bttStartApp = new javax.swing.JButton();
        logo = new javax.swing.JLabel();
        labelTexto = new javax.swing.JLabel();
        background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        gifCarregando.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        gifCarregando.setIcon(new javax.swing.ImageIcon(getClass().getResource("/nuvemEstatica2.png"))); // NOI18N
        gifCarregando.setToolTipText("");
        gifCarregando.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        getContentPane().add(gifCarregando, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 230, 190, 160));

        bttRetornar.setBackground(new java.awt.Color(0, 0, 0));
        bttRetornar.setForeground(new java.awt.Color(255, 255, 255));
        bttRetornar.setText("Voltar");
        bttRetornar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttRetornarActionPerformed(evt);
            }
        });
        getContentPane().add(bttRetornar, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 450, 80, 30));

        bttStopApp.setBackground(new java.awt.Color(0, 0, 0));
        bttStopApp.setForeground(new java.awt.Color(255, 255, 255));
        bttStopApp.setText("Stop");
        bttStopApp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttStopAppActionPerformed(evt);
            }
        });
        getContentPane().add(bttStopApp, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 410, 120, 40));

        bttStartApp.setBackground(new java.awt.Color(0, 0, 0));
        bttStartApp.setForeground(new java.awt.Color(255, 255, 255));
        bttStartApp.setText("Start");
        bttStartApp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttStartAppActionPerformed(evt);
            }
        });
        getContentPane().add(bttStartApp, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 410, 120, 40));

        logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Logo_Observium_Branco.png"))); // NOI18N
        getContentPane().add(logo, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 50, -1, -1));

        labelTexto.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        labelTexto.setForeground(new java.awt.Color(255, 255, 255));
        labelTexto.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelTexto.setText("Captura de dados.");
        getContentPane().add(labelTexto, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 160, 610, 70));

        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/FundoObservium2.jpg"))); // NOI18N
        background.setText("jLabel1");
        getContentPane().add(background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 610, 490));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bttStartAppActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttStartAppActionPerformed
        bttStartApp.setEnabled(false);
        bttStopApp.setEnabled(true);
        AppMonitoramento aplicacao = new AppMonitoramento();
        
        timer = new Timer();
        
        try {
            int delay = 2000;   // tempo de espera antes da 1ª execução da tarefa.
            int interval = 3000;  // intervalo no qual a tarefa será executada.
            
            timer.scheduleAtFixedRate(new TimerTask() {
                public void run() {
                    
                    try {                        
                        labelTexto.setForeground(azulObservium);
                        gifCarregando.setIcon(new javax.swing.ImageIcon(getClass().getResource("/loadingNuvem.gif")));
                        labelTexto.setText("Captura de dados iniciada...");
                        aplicacao.aplicacao();
                        
                    } catch (UnknownHostException ex) {
                        Logger.getLogger(TelaCaptura.class.getName()).log(Level.SEVERE, null, ex);
                    } catch (SocketException ex) {
                        Logger.getLogger(TelaCaptura.class.getName()).log(Level.SEVERE, null, ex);
                    } catch (Exception ex) {
                        Logger.getLogger(TelaCaptura.class.getName()).log(Level.SEVERE, null, ex);
                    }
                    
                }
                
            }, delay, interval);
            
        } catch (java.lang.NumberFormatException ex) {
            labelTexto.setForeground(Color.red);
            labelTexto.setText("Máquina não cadastrada.");
        } 
        
    }//GEN-LAST:event_bttStartAppActionPerformed

    private void bttRetornarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttRetornarActionPerformed
        timer.cancel();
        
        UsuarioCrud usuario = new UsuarioCrud(dataSource);

        String nomeUsuario = usuario.buscarNomeUsuario(login);
        usuario.setUsuario(nomeUsuario);
        TelaFuncMaq funcMaq = new TelaFuncMaq(usuario);
        this.dispose();
        funcMaq.setVisible(true);
    }//GEN-LAST:event_bttRetornarActionPerformed

    private void bttStopAppActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttStopAppActionPerformed
        bttStartApp.setEnabled(true);
        bttStopApp.setEnabled(false);
        timer.cancel();
        labelTexto.setForeground(Color.white);
        gifCarregando.setIcon(new javax.swing.ImageIcon(getClass().getResource("/nuvemEstatica2.png")));
        labelTexto.setText("Captura de dados encerrada...");
    }//GEN-LAST:event_bttStopAppActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaCaptura.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaCaptura.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaCaptura.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaCaptura.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaCaptura().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel background;
    private javax.swing.JButton bttRetornar;
    private javax.swing.JButton bttStartApp;
    private javax.swing.JButton bttStopApp;
    private javax.swing.JLabel gifCarregando;
    private javax.swing.JLabel labelTexto;
    private javax.swing.JLabel logo;
    // End of variables declaration//GEN-END:variables
}
