package TelasAplicacao;

import Usuarios.UsuarioCrud;
import org.apache.commons.dbcp2.BasicDataSource;
import TelasAplicacao.TelaFuncMaq;
import java.awt.Color;

public class TelaLoginFunc extends javax.swing.JFrame {

    /**
     * Creates new form TelaLoginFunc
     */
    public TelaLoginFunc() {
        initComponents();
        setLocationRelativeTo(this);
        logo.requestFocusInWindow();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bttLogin = new javax.swing.JButton();
        codigoUsuario = new javax.swing.JTextField();
        resultadoLogin = new javax.swing.JLabel();
        senhaUsuario = new javax.swing.JPasswordField();
        logo = new javax.swing.JLabel();
        labelUsuario = new javax.swing.JLabel();
        labelSenha = new javax.swing.JLabel();
        background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(610, 490));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        bttLogin.setBackground(new java.awt.Color(0, 0, 0));
        bttLogin.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        bttLogin.setForeground(new java.awt.Color(255, 255, 255));
        bttLogin.setText("Login");
        bttLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttLoginActionPerformed(evt);
            }
        });
        getContentPane().add(bttLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 360, 220, 40));

        codigoUsuario.setForeground(new java.awt.Color(153, 153, 153));
        codigoUsuario.setText("Insira seu nome de usuário");
        codigoUsuario.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                codigoUsuarioFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                codigoUsuarioFocusLost(evt);
            }
        });
        codigoUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                codigoUsuarioActionPerformed(evt);
            }
        });
        getContentPane().add(codigoUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 210, 220, 40));

        resultadoLogin.setForeground(new java.awt.Color(255, 255, 255));
        resultadoLogin.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        getContentPane().add(resultadoLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(175, 430, 250, -1));

        senhaUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                senhaUsuarioActionPerformed(evt);
            }
        });
        getContentPane().add(senhaUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 290, 220, 40));

        logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Logo_Observium_Branco.png"))); // NOI18N
        getContentPane().add(logo, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 40, -1, -1));

        labelUsuario.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        labelUsuario.setForeground(new java.awt.Color(255, 255, 255));
        labelUsuario.setText("Usuário:");
        getContentPane().add(labelUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 190, -1, -1));

        labelSenha.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        labelSenha.setForeground(new java.awt.Color(255, 255, 255));
        labelSenha.setText("Senha:");
        getContentPane().add(labelSenha, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 270, -1, -1));

        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/FundoObservium1.jpg"))); // NOI18N
        background.setText("jLabel1");
        getContentPane().add(background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 610, 490));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bttLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttLoginActionPerformed
        BasicDataSource dataSource = new BasicDataSource();

        UsuarioCrud usuario = new UsuarioCrud(dataSource);

        String usuarioLogin = codigoUsuario.getText();
        String usuarioSenha = senhaUsuario.getText();
        
        //CHAMANDO UM MÉTODO PARA VALIDAR O USUÁRIO QUE ESTÁ TENTANDO LOGAR
        String login = usuario.validarUsuario(usuarioLogin, usuarioSenha).toString().replace("[{=", "");
        login = login.replace("}]", "");

        switch (login) {
            case "1":
                String nome = usuario.buscarNomeUsuario(usuarioLogin);
                usuario.setUsuario(nome);
                TelaFuncMaq registro = new TelaFuncMaq(usuario);
                // Inserindo os dados do usuário que acabou de logar no banco de dados local
                usuario.inserindoUsuarioNoLocal(usuarioLogin);
                this.dispose();
                registro.setVisible(true);
                break;

            default:
                resultadoLogin.setText("Usuário ou senha incorreto.");
                break;
        }

    }//GEN-LAST:event_bttLoginActionPerformed

    private void codigoUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_codigoUsuarioActionPerformed

    }//GEN-LAST:event_codigoUsuarioActionPerformed

    private void senhaUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_senhaUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_senhaUsuarioActionPerformed

    private void codigoUsuarioFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_codigoUsuarioFocusGained
        // TODO add your handling code here:
        if (codigoUsuario.getText().equals("Insira seu nome de usuário")) {
            codigoUsuario.setText("");
            codigoUsuario.setForeground(new Color(102, 102, 102));
        }
    }//GEN-LAST:event_codigoUsuarioFocusGained

    private void codigoUsuarioFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_codigoUsuarioFocusLost
        // TODO add your handling code here:
        if (codigoUsuario.getText().equals("")) {
            codigoUsuario.setText("Insira seu nome de usuário");
            codigoUsuario.setForeground(new Color(153, 153, 153));
        }
    }//GEN-LAST:event_codigoUsuarioFocusLost

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaLoginFunc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaLoginFunc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaLoginFunc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaLoginFunc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaLoginFunc().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel background;
    private javax.swing.JButton bttLogin;
    private javax.swing.JTextField codigoUsuario;
    private javax.swing.JLabel labelSenha;
    private javax.swing.JLabel labelUsuario;
    private javax.swing.JLabel logo;
    private javax.swing.JLabel resultadoLogin;
    private javax.swing.JPasswordField senhaUsuario;
    // End of variables declaration//GEN-END:variables
}
