package TelasAplicacao;

import Maquina.Maquina;
import Maquina.MaquinaCrud;
import Componentes.Componente;
import Componentes.ComponenteCrud;
import Componentes.Cpu;
import Componentes.Disco;
import Componentes.Memory;
import Usuarios.UsuarioCrud;
import java.net.SocketException;
import java.net.UnknownHostException;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import org.apache.commons.dbcp2.BasicDataSource;
import java.awt.Color;
import java.awt.Image;
import java.awt.Toolkit;
import java.net.URL;
import javax.swing.JOptionPane;

/**
 *
 * @author aluno
 */
public class TelaCadMaq extends javax.swing.JFrame {

    public String login;
    public String nome;
    public Boolean hasPcNuvem;
    public Boolean hasPcLocal;
    public String localidade;

    public String getLocalidade() {
        return localidade;
    }

    public void setLocalidade(String localidade) {
        this.localidade = localidade;
    }
    
    public Boolean getHasPcNuvem() {
        return hasPcNuvem;
    }

    public void setHasPcNuvem(Boolean hasPcNuvem) {
        this.hasPcNuvem = hasPcNuvem;
    }

    public Boolean getHasPcLocal() {
        return hasPcLocal;
    }

    public void setHasPcLocal(Boolean hasPcLocal) {
        this.hasPcLocal = hasPcLocal;
    }
    
    BasicDataSource dataSource = new BasicDataSource();
    MaquinaCrud maquinaCrud = new MaquinaCrud(dataSource);
    
    public TelaCadMaq() {
        initComponents();
        setLocationRelativeTo(this);
    }
    
    public TelaCadMaq(UsuarioCrud usuario) throws UnknownHostException {
        initComponents();
        setLocationRelativeTo(this);

        URL url = this.getClass().getResource("/logoIcon.png");
        Image imagemTitulo = Toolkit.getDefaultToolkit().getImage(url);
        this.setIconImage(imagemTitulo);
        
        login = usuario.getLoginUsuario();
        nome = usuario.getUsuario();
        
        String hostName = maquinaCrud.buscarHostName();
        
        setHasPcNuvem(maquinaCrud.verificarMaquinaNuvem(hostName));
        setHasPcLocal(maquinaCrud.verificarMaquinaLocal(hostName));
        
        if (getHasPcNuvem().equals(true) || getHasPcLocal().equals(true)) {
            titulo.setText("Localidade já registrada:");
            
            if (getHasPcNuvem().equals(true)) {
                setLocalidade(maquinaCrud.buscarLocalMaqNuvem(hostName));
            } else {
                setLocalidade(maquinaCrud.buscarLocalMaqLocal(hostName));
            }
            
            Integer referencia = getLocalidade().indexOf("-");
            
            if (getLocalidade().substring(0, referencia).equals("recepcao")) {
                comboBoxSetor.setSelectedIndex(0);
            } else if (getLocalidade().substring(0, referencia).equals("triagem")) {
                comboBoxSetor.setSelectedIndex(1);
            } else {
                comboBoxSetor.setSelectedIndex(2);
            }
            
            numeroAndar.setText(getLocalidade().substring(referencia + 1));
            
            comboBoxSetor.setEnabled(false);
            numeroAndar.setEnabled(false);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bttRetornar = new javax.swing.JButton();
        titulo = new javax.swing.JLabel();
        setor = new javax.swing.JLabel();
        andar = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        bttCadastrar = new javax.swing.JButton();
        comboBoxSetor = new javax.swing.JComboBox<>();
        numeroAndar = new javax.swing.JTextField();
        background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        bttRetornar.setBackground(new java.awt.Color(0, 0, 0));
        bttRetornar.setForeground(new java.awt.Color(255, 255, 255));
        bttRetornar.setText("Voltar");
        bttRetornar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttRetornarActionPerformed(evt);
            }
        });
        getContentPane().add(bttRetornar, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 450, 80, 30));

        titulo.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        titulo.setForeground(new java.awt.Color(255, 255, 255));
        titulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titulo.setText("Registrar localidade:");
        titulo.setPreferredSize(new java.awt.Dimension(149, 20));
        getContentPane().add(titulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 180, 450, 40));

        setor.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        setor.setForeground(new java.awt.Color(255, 255, 255));
        setor.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        setor.setText("Setor:");
        setor.setPreferredSize(new java.awt.Dimension(149, 20));
        getContentPane().add(setor, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 230, 70, 40));

        andar.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        andar.setForeground(new java.awt.Color(255, 255, 255));
        andar.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        andar.setText("Andar:");
        andar.setPreferredSize(new java.awt.Dimension(149, 20));
        getContentPane().add(andar, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 310, 60, 40));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Logo_Observium_Branco.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 50, -1, -1));

        bttCadastrar.setBackground(new java.awt.Color(0, 0, 0));
        bttCadastrar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        bttCadastrar.setForeground(new java.awt.Color(255, 255, 255));
        bttCadastrar.setText("Concluir Cadastro");
        bttCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttCadastrarActionPerformed(evt);
            }
        });
        getContentPane().add(bttCadastrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 410, 190, 40));

        comboBoxSetor.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Recepção", "Triagem", "Ala médica" }));
        comboBoxSetor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboBoxSetorActionPerformed(evt);
            }
        });
        getContentPane().add(comboBoxSetor, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 270, 190, 40));

        numeroAndar.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        numeroAndar.setText("00");
        numeroAndar.setToolTipText("");
        getContentPane().add(numeroAndar, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 350, 60, 40));

        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/FundoObservium2.jpg"))); // NOI18N
        background.setText("jLabel1");
        getContentPane().add(background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 610, 490));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void comboBoxSetorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboBoxSetorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboBoxSetorActionPerformed

    private void bttCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttCadastrarActionPerformed
        try {
            UsuarioCrud usuario = new UsuarioCrud(dataSource);

            //==========================COMPUTADOR==============================
            //INSTANCIANDO A CLASSE MAQUINA CRUD
            MaquinaCrud computador = new MaquinaCrud(dataSource);
            
            //OBTENDO INFORMAÇÕES DO COMPUTADOR E GUARDANDO EM VARIAVEIS
            String hostName = computador.buscarHostName();
            String endMac = computador.buscarEndMac();
            String fabricante = computador.buscarFabricante();
            Integer arquitetura = computador.buscarArquitetura();
            String sistemaOperacional = computador.buscarSO();
            
            if (getHasPcNuvem().equals(true) || getHasPcLocal().equals(true)) {
                if (getHasPcNuvem().equals(true)) {
                    setLocalidade(computador.buscarLocalMaqNuvem(hostName));
                } else {
                    setLocalidade(computador.buscarLocalMaqLocal(hostName));
                }
            } else {
                //OBTENDO INFORMAÇÕES SOBRE A LOCALIDADE DA MÁQUINA
                String andarMaquina = numeroAndar.getText();

                Object objectSetor = comboBoxSetor.getSelectedItem();
                String setor = String.valueOf(objectSetor);

                if (setor.equals("Recepção")) {
                    setLocalidade("recepcao-" + andarMaquina);
                } else if (setor.equals("Triagem")) {
                    setLocalidade("triagem-" + andarMaquina);
                } else {
                    setLocalidade("alaMedica-" + andarMaquina);
                }
            }
            
            //BUSCANDO O ID DO HOSPITAL DO USUÁRIO LOGADO PARA CADASTRAR A MÁQUINA
            Integer fkHospital = usuario.buscarIdHospitalNuvem(login);
            
            try {
                //INSERINDO COMPUTADOR NO BANCO COM AS INFORMAÇÕES OBTIDAS
                Maquina maquina = new Maquina(hostName, endMac, fabricante,
                    arquitetura, sistemaOperacional, getLocalidade(), fkHospital);
                
                if (getHasPcNuvem().equals(false)) {
                    computador.incluirNuvem(maquina); //INCLUIR NO BANCO NA NUVEM
                }
                
                if (getHasPcLocal().equals(false)) {
                    computador.incluirLocal(maquina); //INCLUIR NO BANCO LOCAL
                }
                
                //========================COMPONENTES===========================
                ComponenteCrud componentes = new ComponenteCrud(dataSource);
                
                Cpu cpu = new Cpu();
                Memory memory = new Memory();
                Disco disco = new Disco();
                
                Integer idPcNuvem = computador.buscarIdComputadorNuvem(hostName);
                Integer idPcLocal = computador.buscarIdComputadorLocal(hostName);
                
                //INSERINDO CPU NO LOCAL
                String nomeCpu = cpu.buscarNomeCpu();
                
                if (getHasPcNuvem().equals(false)) {
                    Componente cpuNuvem = new Componente(nomeCpu, "CPU", idPcNuvem);
                    componentes.incluirComponenteNuvem(cpuNuvem); //INCLUIR NA NUVEM
                }
                
                if (getHasPcLocal().equals(false)) {
                    Componente cpuLocal = new Componente(nomeCpu, "CPU", idPcLocal);
                    componentes.incluirComponenteLocal(cpuLocal); //INCLUIR NO BANCO
                }
                
                //INSERINDO MEMÓRIA
                String nomeMemoria = memory.buscarNomeMemoria();
                
                if (getHasPcNuvem().equals(false)) {
                    Componente memoriaNuvem = new Componente(nomeMemoria, "MEMORIA", idPcNuvem);
                    componentes.incluirComponenteNuvem(memoriaNuvem); //INCLUIR NA NUVEM
                }
                
                if (getHasPcLocal().equals(false)) {
                    Componente memoriaLocal = new Componente(nomeMemoria, "MEMORIA", idPcLocal);
                    componentes.incluirComponenteLocal(memoriaLocal); //INCLUIR NO BANCO
                }
                
                //INSERINDO DISCO
                String nomeDisco = disco.buscarNomeDisco();
                
                if (getHasPcNuvem().equals(false)) {
                    Componente discoNuvem = new Componente(nomeDisco, "DISCO", idPcNuvem);
                    componentes.incluirComponenteNuvem(discoNuvem); //INCLUIR NA NUVEM
                }
                
                if (getHasPcLocal().equals(false)) {
                    Componente discoLocal = new Componente(nomeDisco, "DISCO", idPcLocal);
                    componentes.incluirComponenteLocal(discoLocal); //INCLUIR NO BANCO
                }
                
                if (getHasPcLocal().equals(false) && getHasPcNuvem().equals(false)) {
                    JOptionPane.showMessageDialog(this, "Máquina cadastrada com sucesso"
                            + "\nna Nuvem e no Banco Local!");
                } else if (getHasPcLocal().equals(false)) {
                    JOptionPane.showMessageDialog(this, "Máquina cadastrada no"
                            + "\nBanco Local com sucesso!");
                } else {
                    JOptionPane.showMessageDialog(this, "Máquina cadastrada na"
                            + "\nNuvem com sucesso!");
                }
                
                String nomeUsuario = usuario.buscarNomeUsuario(login);
                usuario.setUsuario(nomeUsuario);
                TelaFuncMaq funcMaq = new TelaFuncMaq(usuario);
                this.dispose();
                funcMaq.setVisible(true);
            } catch (org.springframework.dao.DuplicateKeyException exception) {
                JOptionPane.showMessageDialog(this, "Máquina já cadastrada na"
                        + "\nNuvem e no Banco Local!");
                
                String nomeUsuario = usuario.buscarNomeUsuario(login);
                usuario.setUsuario(nomeUsuario);
                TelaFuncMaq funcMaq = new TelaFuncMaq(usuario);
                this.dispose();
                funcMaq.setVisible(true);
            }

        } catch (UnknownHostException ex) {
            Logger.getLogger(TelaFuncMaq.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SocketException ex) {
            Logger.getLogger(TelaFuncMaq.class.getName()).log(Level.SEVERE, null, ex);
        }
            
    }//GEN-LAST:event_bttCadastrarActionPerformed

    private void bttRetornarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttRetornarActionPerformed
        UsuarioCrud usuario = new UsuarioCrud(dataSource);
        
        String nomeUsuario = usuario.buscarNomeUsuario(login);
        usuario.setUsuario(nomeUsuario);
        TelaFuncMaq funcMaq = new TelaFuncMaq(usuario);
        this.dispose();
        funcMaq.setVisible(true);
    }//GEN-LAST:event_bttRetornarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaCadMaq.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaCadMaq.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaCadMaq.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaCadMaq.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaCadMaq().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel andar;
    private javax.swing.JLabel background;
    private javax.swing.JButton bttCadastrar;
    private javax.swing.JButton bttRetornar;
    private javax.swing.JComboBox<String> comboBoxSetor;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField numeroAndar;
    private javax.swing.JLabel setor;
    private javax.swing.JLabel titulo;
    // End of variables declaration//GEN-END:variables
}
